# Generated by Django 3.2.5 on 2021-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registertble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('paswd', models.CharField(max_length=32)),
                ('repaswd', models.CharField(max_length=32)),
                ('chk_box', models.BooleanField(default=False)),
            ],
        ),
    ]
